# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    if: github.actor == 'pasichDev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet

      - name: Prepare artifact
        run: |
          mkdir -p release
          mv rpc wallet release/
          tar -czvf release/SovaCLI-ubuntu-latest-x86_64.tar.gz -C release .
          ls -l release 

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-ubuntu
          path: release/SovaCLI-ubuntu-latest-x86_64.tar.gz

  build-windows:
    if: github.actor == 'pasichDev'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc.exe
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet.exe

      - name: Prepare artifact
        run: |
          mkdir release
          mv rpc.exe wallet.exe release/
          Compress-Archive -Path release\* -DestinationPath release\SovaCLI-windows-latest-x86_64.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-windows
          path: release\SovaCLI-windows-latest-x86_64.zip

  build-macos:
    if: github.actor == 'pasichDev'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet

      - name: Prepare artifact
        run: |
          mkdir -p release
          mv rpc wallet release/
          tar -czvf release/SovaCLI-macos-latest-x86_64.tar.gz -C release .
          ls -l release 

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-macos
          path: release/SovaCLI-macos-latest-x86_64.tar.gz
