# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.actor == 'pasichDev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3' # Вкажіть необхідну версію Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Compile Dart CLI
        run: dart compile exe rpc.dart -o rpc

      - name: Prepare artifact
        run: |
          mkdir -p release
          mv rpc release/
          tar -czvf release/rpc_ubuntu.tar.gz -C release rpc

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpc-output
          path: release/rpc_ubuntu.tar.gz

  release:
    if: github.actor == 'pasichDev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/rpc_ubuntu.tar.gz
          asset_name: rpc_ubuntu_${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
