# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
     - "doc/**"
     - "tool/**"
     - ".vscode/**"
     - 'README.md'
     - '.gitignore'
     - 'analysis_options.yaml'
     - 'devtools_options.yaml'
     - 'LICENSE'

jobs:
  build-ubuntu:
    if: github.actor == 'pasichDev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
     # - name: Analyze code
      #  run: dart analyze
       # continue-on-error: false
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet
        
      - name: Prepare artifact
        run: |
          mkdir -p sova-cli/
          mv rpc wallet CHANGELOG.md LICENSE sova-cli/
          cd sova-cli
          tar -czvf SovaCLI-ubuntu-latest-x86_64.tar.gz *
          cd ..
          ls -l sova-cli

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-ubuntu
          path: sova-cli/SovaCLI-ubuntu-latest-x86_64.tar.gz

  build-windows:
    if: github.actor == 'pasichDev'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze
        continue-on-error: false
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc.exe
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet.exe

      - name: Prepare artifact
        run: |
          mkdir -p sova-cli/
          Move-Item -Path rpc.exe -Destination sova-cli/
          Move-Item -Path wallet.exe -Destination sova-cli/
          Move-Item -Path LICENSE -Destination sova-cli/
          Move-Item -Path CHANGELOG.md -Destination sova-cli/
          Compress-Archive -Path sova-cli\* -DestinationPath sova-cli\SovaCLI-windows-latest-x86_64.zip
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-windows
          path: sova-cli\SovaCLI-windows-latest-x86_64.zip

  build-macos-x64:
    if: github.actor == 'pasichDev'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with: 
          architecture: x64

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze
        continue-on-error: false
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet

      - name: Prepare artifact
        run: |
          mkdir -p sova-cli/
          mv rpc wallet CHANGELOG.md LICENSE sova-cli/
          cd sova-cli
          tar -czvf SovaCLI-macos-x64-latest.tar.gz *
          cd ..
          ls -l sova-cli

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-ubuntu
          path: sova-cli/SovaCLI-macos-x64-latest.tar.gz

  build-macos-arm64:
    if: github.actor == 'pasichDev'
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with: 
          architecture: arm64

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze
        continue-on-error: false
        
      - name: Compile RPC
        run: dart compile exe bin/rpc.dart -o rpc
        
      - name: Compile Wallet
        run: dart compile exe bin/wallet.dart -o wallet

      - name: Prepare artifact
        run: |
          mkdir -p sova-cli/
          mv rpc wallet CHANGELOG.md LICENSE sova-cli/
          cd sova-cli
          tar -czvf SovaCLI-macos-arm64-latest.tar.gz *
          cd ..
          ls -l sova-cli

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sova-cli-ubuntu
          path: sova-cli/SovaCLI-macos-arm64-latest.tar.gz
